import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms & Disclaimer — Hunger Games Simulator',
  description: 'Terms of use and fan-project disclaimer for Hunger Games Simulator, including simulation results, intellectual property, and acceptable use.',
  alternates: { canonical: '/terms' },
};

const h2: React.CSSProperties = { fontFamily: 'Cinzel, serif', color: '#e8e0d0', fontSize: '1.1rem', margin: '1.75rem 0 0.75rem' };
const p: React.CSSProperties = { marginBottom: '1.1rem' };

export default function TermsPage() {
  return (
    <div style={{maxWidth:'800px',margin:'0 auto',padding:'2rem 1rem'}}>
      <nav style={{display:'flex',gap:'0.5rem',fontSize:'0.7rem',color:'#5a5448',marginBottom:'1.25rem'}}>
        <Link href="/" style={{color:'#d4a017',textDecoration:'none'}}>Home</Link><span>/</span><span style={{color:'#a09880'}}>Terms & Disclaimer</span>
      </nav>
      <h1 style={{fontFamily:'Cinzel, Georgia, serif',fontWeight:900,fontSize:'clamp(1.75rem,4vw,2.5rem)',margin:'0 0 1.5rem'}}>Terms of Use & Disclaimer</h1>
      <div style={{color:'#a09880',lineHeight:1.9,fontSize:'0.95rem'}}>
        <p style={p}><strong style={{color:'#e8e0d0'}}>Last updated: October 9, 2026.</strong> By accessing or using Hunger Games Simulator (&ldquo;the Site&rdquo;), you agree to these Terms of Use. If you do not agree, please do not use the Site.</p>

        <h2 style={h2}>1. Fan Project — No Affiliation</h2>
        <p style={p}>This is an independent, unofficial fan project created for entertainment and commentary. Hunger Games Simulator is not affiliated with, endorsed by, sponsored by, or connected to Suzanne Collins, Scholastic Press, Lionsgate Entertainment, or any of their partners, subsidiaries, or licensors. Any references to the Hunger Games franchise are made for purposes of fan commentary and discussion.</p>

        <h2 style={h2}>2. Intellectual Property</h2>
        <p style={p}>The Hunger Games franchise — including its characters, names, settings, and story elements — belongs to its respective rights holders. This Site does not claim ownership of those elements. All original content on the Site — including simulation software, stat scoring, editorial articles, and site design — is the work of this Site&rsquo;s authors. Character statistics, odds, and matchup commentary are original transformative analysis created by our editorial team.</p>
        <p style={p}>If you are a rights holder and believe any content on the Site infringes your rights, please contact us through the <Link href="/contact" style={{color:'#d4a017'}}>Contact page</Link> (select &ldquo;Copyright / DMCA notice&rdquo;) with details of the work, the URL, and your contact information. We respond to valid notices promptly.</p>

        <h2 style={h2}>3. Simulation Results Are Fictional</h2>
        <p style={p}>Simulation outcomes, matchup results, victory odds, quiz rankings, and leaderboard positions are generated by this Site&rsquo;s own algorithms for entertainment. They are not official predictions, canonical outcomes, or statements by the franchise&rsquo;s rights holders. Do not rely on them for any decision beyond enjoying a fan game.</p>

        <h2 style={h2}>4. Acceptable Use</h2>
        <p style={p}>You agree to use the Site lawfully and only for its intended purposes. You agree not to: attempt to disrupt the Site&rsquo;s operation; scrape or copy substantial portions of the Site&rsquo;s original content for republication; abuse automated access; attempt to gain unauthorized access to any system; or use the Site in a way that infringes the rights of others.</p>

        <h2 style={h2}>5. No Accounts; Minimum Age Guidance</h2>
        <p style={p}>The Site requires no account or login. The Site is intended for a general audience. If you are under the age required to consent to online services in your jurisdiction, please use the Site only with a parent or guardian&rsquo;s permission and do not submit personal information through the contact channels.</p>

        <h2 style={h2}>6. Third-Party Services and Advertising</h2>
        <p style={p}>The Site may display advertising served by Google AdSense and may use third-party services such as Google Fonts. Those providers operate under their own terms and privacy policies. Please review our <Link href="/privacy" style={{color:'#d4a017'}}>Privacy Policy</Link> for details on cookies, advertising technologies, and your choices.</p>

        <h2 style={h2}>7. External Links</h2>
        <p style={p}>The Site may link to third-party websites for reference. We do not control those sites and are not responsible for their content, policies, or practices.</p>

        <h2 style={h2}>8. Disclaimer of Warranties</h2>
        <p style={p}>The Site is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied, including warranties of accuracy, reliability, or fitness for a particular purpose. We do not guarantee that the Site will be uninterrupted, error-free, or free of harmful components.</p>

        <h2 style={h2}>9. Limitation of Liability</h2>
        <p style={p}>To the maximum extent permitted by law, the Site&rsquo;s operators will not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of (or inability to use) the Site.</p>

        <h2 style={h2}>10. Changes to These Terms</h2>
        <p style={p}>We may update these Terms when the Site or applicable requirements change. The &ldquo;Last updated&rdquo; date above will be revised for material changes, and continued use of the Site after changes take effect constitutes acceptance of the updated Terms.</p>

        <h2 style={h2}>11. Contact</h2>
        <p style={p}>For questions about these Terms, copyright concerns, or anything else, please use the <Link href="/contact" style={{color:'#d4a017'}}>Contact page</Link>.</p>
      </div>
    </div>
  );
}
