import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms & Disclaimer — Hunger Games Simulator',
  description: 'Terms of use and fan-project disclaimer for Hunger Games Simulator, including simulation results, intellectual property, and acceptable use.',
  alternates: { canonical: '/terms' },
};

export default function TermsPage() {
  return (
    <div style={{maxWidth:'800px',margin:'0 auto',padding:'2rem 1rem'}}>
      <nav style={{display:'flex',gap:'0.5rem',fontSize:'0.7rem',color:'#5a5448',marginBottom:'1.25rem'}}>
        <Link href="/" style={{color:'#d4a017',textDecoration:'none'}}>Home</Link><span>/</span><span style={{color:'#a09880'}}>Terms & Disclaimer</span>
      </nav>
      <h1 style={{fontFamily:'Cinzel, Georgia, serif',fontWeight:900,fontSize:'clamp(1.75rem,4vw,2.5rem)',margin:'0 0 1.5rem'}}>Terms & Disclaimer</h1>
      <div style={{color:'#a09880',lineHeight:1.9,fontSize:'0.95rem'}}>
        <p style={{marginBottom:'1.25rem'}}><strong>Last updated: September 21, 2026</strong></p>
        <h2>1. Fan Project</h2>
        <p>This is an independent, unofficial fan project. Hunger Games Simulator is not affiliated with, endorsed by, or sponsored by Suzanne Collins, Scholastic, Lionsgate, or their respective partners.</p>
        <h2>2. Intellectual Property</h2>
        <p>The Hunger Games franchise, its characters, settings, names, and related story elements belong to their respective rights holders. This site does not claim ownership of those elements.</p>
        <h2>3. Simulation Results</h2>
        <p>Simulation, matchup, and odds results are generated by this site's own algorithms and are fictional entertainment outputs. They are not official predictions, canon results, or statements made by the franchise's rights holders.</p>
        <h2>4. Acceptable Use</h2>
        <p>Use the website lawfully and do not attempt to interfere with its operation, abuse automated services, or use the site to violate another person's rights.</p>
        <h2>5. Contact</h2>
        <p>For copyright or other concerns, please use the <Link href="/contact" style={{color:'#d4a017'}}>Contact page</Link>.</p>
      </div>
    </div>
  );
}
