'use client';

import type { CSSProperties } from 'react';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { runSimulationLab, arenaPresets, type ArenaConfig } from '@/lib/advanced-simulation';
import { tributes } from '@/data/tributes';

export default function SimulationLabContent() {
  const [selected, setSelected] = useState(tributes.map(t=>t.id));
  const [count, setCount] = useState(10000);
  const [preset, setPreset] = useState(0);
  const [mode, setMode] = useState<'dynamic'|'aggressive'|'survival'|'balanced'>('dynamic');
  const [result, setResult] = useState<ReturnType<typeof runSimulationLab>|null>(null);
  const [running, setRunning] = useState(false);
  const arena = arenaPresets[preset] as ArenaConfig;
  const selectedTributes = useMemo(()=>tributes.filter(t=>selected.includes(t.id)),[selected]);

  const run = () => {
    if (selected.length < 2) return;
    setRunning(true);
    window.setTimeout(()=>{ setResult(runSimulationLab(selected, count, arena, mode)); setRunning(false); }, 20);
  };
  const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.length>2?s.filter(x=>x!==id):s:[...s,id]);

  return <main style={{maxWidth:1300,margin:'0 auto',padding:'2rem 1rem 5rem'}}>
    <Link href="/" style={{color:'#d4a017',fontSize:'.7rem',textDecoration:'none'}}>HOME /</Link>
    <p style={{color:'#d4a017',fontFamily:'Oswald',letterSpacing:'.35em',fontSize:'.62rem',margin:'1rem 0 .4rem'}}>📊 ADVANCED ANALYTICS</p>
    <h1 style={{fontFamily:'Cinzel,serif',fontSize:'clamp(2rem,5vw,3.2rem)',margin:'0 0 .5rem'}}>10,000 Simulation Lab</h1>
    <p style={{color:'#a09880',maxWidth:760,lineHeight:1.7}}>Run thousands of independent Games with the advanced strategy engine and analyze the results statistically. These figures are generated by this simulator and are not canon probabilities.</p>

    <section className="lab-grid" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 300px',gap:'1rem',marginTop:'1.5rem'}}>
      <div style={{background:'#0d1009',border:'1px solid #1e2818',borderRadius:10,padding:'1rem'}}>
        <h2 style={{fontFamily:'Cinzel,serif',fontSize:'1rem'}}>Tribute Pool</h2>
        <div style={{display:'flex',gap:'.4rem',flexWrap:'wrap'}}>{tributes.map(t=><button key={t.id} onClick={()=>toggle(t.id)} style={{background:selected.includes(t.id)?'rgba(212,160,23,.1)':'transparent',border:`1px solid ${selected.includes(t.id)?'rgba(212,160,23,.5)':'#1e2818'}`,color:selected.includes(t.id)?'#d4a017':'#5a5448',padding:'.3rem .5rem',borderRadius:3,cursor:'pointer',fontSize:'.62rem'}}>{t.name}</button>)}</div>
        <p style={{color:'#5a5448',fontSize:'.65rem',marginTop:'.7rem'}}>{selectedTributes.length} tributes selected</p>
      </div>
      <aside style={{background:'#0d1009',border:'1px solid #1e2818',borderRadius:10,padding:'1rem'}}>
        <label style={{display:'block',color:'#a09880',fontSize:'.68rem',marginBottom:'.35rem'}}>SIMULATIONS</label>
        <select value={count} onChange={e=>setCount(Number(e.target.value))} style={input}>{[1000,2500,5000,10000].map(n=><option key={n} value={n}>{n.toLocaleString()}</option>)}</select>
        <label style={label}>ARENA</label><select value={preset} onChange={e=>setPreset(Number(e.target.value))} style={input}>{arenaPresets.map((a,i)=><option key={a.name} value={i}>{a.name}</option>)}</select>
        <label style={label}>AI MODE</label><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} style={input}><option value="dynamic">Dynamic</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option><option value="survival">Survival</option></select>
        <button onClick={run} disabled={running||selected.length<2} style={{width:'100%',marginTop:'1rem',padding:'.75rem',border:0,borderRadius:4,background:'linear-gradient(135deg,#d4a017,#b8860b)',fontFamily:'Oswald',fontWeight:700,cursor:running?'wait':'pointer'}}>{running?'RUNNING…':'RUN SIMULATIONS'}</button>
      </aside>
    </section>

    {result && <section style={{marginTop:'1.5rem',background:'#0d1009',border:'1px solid #1e2818',borderRadius:10,overflow:'auto'}}>
      <div style={{padding:'1rem',borderBottom:'1px solid #1e2818'}}><h2 style={{fontFamily:'Cinzel,serif',margin:0}}>Results — {result.simulations.toLocaleString()} Games</h2><p style={{color:'#5a5448',fontSize:'.68rem'}}>Arena: {result.arena.name} · Rankings are sorted by simulated win rate.</p></div>
      <table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr>{['#','TRIBUTE','WIN RATE','AVG PLACE','AVG SURVIVAL','AVG KILLS','TOP 3'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{result.rows.map((r,i)=><tr key={r.tributeId}><td style={td}>{i+1}</td><td style={{...td,color:'#e8e0d0',fontFamily:'Cinzel,serif'}}>{r.name}</td><td style={{...td,color:'#d4a017',fontWeight:700}}>{r.winRate}%</td><td style={td}>{r.averagePlacement}</td><td style={td}>Day {r.averageSurvivalDay}</td><td style={td}>{r.averageKills}</td><td style={td}>{r.topThreeRate}%</td></tr>)}</tbody></table>
    </section>}
  </main>;
}
const label={display:'block',color:'#a09880',fontSize:'.68rem',marginTop:'.8rem',marginBottom:'.35rem'} as CSSProperties;
const input={width:'100%',background:'#080a06',color:'#e8e0d0',border:'1px solid #1e2818',borderRadius:4,padding:'.55rem'} as CSSProperties;
const th={textAlign:'left',padding:'.65rem',fontSize:'.55rem',color:'#5a5448',borderBottom:'1px solid #1e2818'} as CSSProperties;
const td={padding:'.65rem',fontSize:'.72rem',color:'#a09880',borderBottom:'1px solid rgba(255,255,255,.03)'} as CSSProperties;
